version: 2

jobs:
  build-miniforge3:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build miniforge image
          command: |
            cd minforge3/ubuntu
            docker build -t condaforge/miniforge3 .
  build-anvil:
    environment:
      DOCKERIMAGE: linux-anvil-comp7
    working_directory: ~/test
    machine: true
    steps:
      - checkout
      - run:
          name: Merge PRs
          command: ./.circleci/checkout_merge_commit.sh
      - run:
          name: Info about provided Docker
          command: docker info
      - run:
          name: Build image
          command: docker build -t condaforge/$DOCKERIMAGE -f $DOCKERIMAGE/Dockerfile --no-cache .
      - run:
          name: Test built image
          command: ./.circleci/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-anvil
      - build-miniforge3
