name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 7 * * *"  # everyday 0700 UTC

jobs:
  build:
    name: ${{ matrix.cfg.DOCKERIMAGE }}:${{ matrix.cfg.DOCKERTAG }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - DOCKERIMAGE: linux-anvil-comp7
          DOCKERTAG: latest
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-cos7-x86_64
          DOCKERTAG: latest
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le
          DOCKERTAG: latest
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-aarch64
          DOCKERTAG: latest
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "9.2"
          CUDA_VER: "9.2"
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "10.0"
          CUDA_VER: "10.0"
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "10.1"
          CUDA_VER: "10.1"
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "10.2"
          CUDA_VER: "10.2"
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-cos7-cuda
          DOCKERFILE: linux-anvil-cuda
          DOCKERTAG: "9.2"
          CUDA_VER: "9.2"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cos7-cuda
          DOCKERFILE: linux-anvil-cuda
          DOCKERTAG: "10.0"
          CUDA_VER: "10.0"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cos7-cuda
          DOCKERFILE: linux-anvil-cuda
          DOCKERTAG: "10.1"
          CUDA_VER: "10.1"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cos7-cuda
          DOCKERFILE: linux-anvil-cuda
          DOCKERTAG: "10.2"
          CUDA_VER: "10.2"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "11.0"
          CUDA_VER: "11.0.3"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "11.1"
          CUDA_VER: "11.1.1"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "11.2"
          CUDA_VER: "11.2.2"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "11.3"
          CUDA_VER: "11.3.1"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "11.4"
          CUDA_VER: "11.4.2"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "9.2"
          CUDA_VER: "9.2"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "10.0"
          CUDA_VER: "10.0"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "10.1"
          CUDA_VER: "10.1"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "10.2"
          CUDA_VER: "10.2"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "11.0"
          CUDA_VER: "11.0.3"
          CENTOS_VER: "8"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "11.1"
          CUDA_VER: "11.1.1"
          CENTOS_VER: "8"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "11.2"
          CUDA_VER: "11.2.2"
          CENTOS_VER: "8"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "11.3"
          CUDA_VER: "11.3.1"
          CENTOS_VER: "8"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "11.4"
          CUDA_VER: "11.4.2"
          CENTOS_VER: "8"

        - DOCKERIMAGE: linux-anvil-aarch64-cuda
          DOCKERTAG: "11.0"
          CUDA_VER: "11.0.3"
          CENTOS_VER: "8"

        - DOCKERIMAGE: linux-anvil-aarch64-cuda
          DOCKERTAG: "11.1"
          CUDA_VER: "11.1.1"
          CENTOS_VER: "8"

        - DOCKERIMAGE: linux-anvil-aarch64-cuda
          DOCKERTAG: "11.2"
          CUDA_VER: "11.2.2"
          CENTOS_VER: "8"

        - DOCKERIMAGE: linux-anvil-aarch64-cuda
          DOCKERTAG: "11.3"
          CUDA_VER: "11.3.1"
          CENTOS_VER: "8"

        - DOCKERIMAGE: linux-anvil-aarch64-cuda
          DOCKERTAG: "11.4"
          CUDA_VER: "11.4.2"
          CENTOS_VER: "8"

    env:
      DOCKERIMAGE: ${{ matrix.cfg.DOCKERIMAGE }}
      DOCKERFILE: ${{ matrix.cfg.DOCKERFILE }}
      DOCKERTAG: ${{ matrix.cfg.DOCKERTAG }}
      CUDA_VER: ${{ matrix.cfg.CUDA_VER }}
      CENTOS_VER: ${{ matrix.cfg.CENTOS_VER }}

    steps:
      - uses: actions/checkout@v2

      - name: Enable experimental features (needed for squash)
        run: |
          sudo cp docker_daemon_config.json /etc/docker/daemon.json
          sudo service docker restart

      - name: Docker info
        run: |
          docker info

      - name: Configure qemu
        run: |
          ./download-qemu-static.sh

      - name: Build image
        run: |
          docker build \
            --build-arg CUDA_VER --build-arg CENTOS_VER \
            -t condaforge/$DOCKERIMAGE:$DOCKERTAG \
            -f ${DOCKERFILE:-${DOCKERIMAGE}}/Dockerfile \
            --no-cache --squash .

      - name: Run image
        run: |
          ./.circleci/run_docker_build.sh

      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.repository == 'conda-forge/docker-images'
        env:
          CFD_QUAY_PASSWORD: ${{ secrets.CFD_QUAY_PASSWORD }}
          DH_PASSWORD: ${{ secrets.DH_PASSWORD }}
        run: |
          ./scripts/deploy
