name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: ${{ matrix.cfg.DOCKERIMAGE }}:${{ matrix.cfg.DOCKERTAG }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
        - DOCKERIMAGE: linux-anvil-comp7
          DOCKERTAG: latest
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-comp7
          DOCKERTAG: jnlp-slave
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-cos7-x86_64
          DOCKERTAG: latest
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le
          DOCKERTAG: latest
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-aarch64
          DOCKERTAG: latest
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "9.2"
          CUDA_VER: "9.2"
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "10.0"
          CUDA_VER: "10.0"
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "10.1"
          CUDA_VER: "10.1"
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "10.2"
          CUDA_VER: "10.2"
          CENTOS_VER: "6"

        - DOCKERIMAGE: linux-anvil-cos7-cuda
          DOCKERFILE: linux-anvil-cuda
          DOCKERTAG: "9.2"
          CUDA_VER: "9.2"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cos7-cuda
          DOCKERFILE: linux-anvil-cuda
          DOCKERTAG: "10.0"
          CUDA_VER: "10.0"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cos7-cuda
          DOCKERFILE: linux-anvil-cuda
          DOCKERTAG: "10.1"
          CUDA_VER: "10.1"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cos7-cuda
          DOCKERFILE: linux-anvil-cuda
          DOCKERTAG: "10.2"
          CUDA_VER: "10.2"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "11.0"
          CUDA_VER: "11.0"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "11.1"
          CUDA_VER: "11.1"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-cuda
          DOCKERTAG: "11.2"
          CUDA_VER: "11.2.0"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "9.2"
          CUDA_VER: "9.2"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "10.0"
          CUDA_VER: "10.0"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "10.1"
          CUDA_VER: "10.1"
          CENTOS_VER: "7"

        - DOCKERIMAGE: linux-anvil-ppc64le-cuda
          DOCKERTAG: "10.2"
          CUDA_VER: "10.2"
          CENTOS_VER: "7"

        - DOCKERIMAGE: miniforge3
          DOCKERFILE: miniforge3
          DOCKERTAG: latest
          MINIFORGE_VARIANT: Miniforge3

        - DOCKERIMAGE: mambaforge
          DOCKERFILE: miniforge3
          DOCKERTAG: latest
          MINIFORGE_VARIANT: Mambaforge

    env:
      DOCKERIMAGE: ${{ matrix.cfg.DOCKERIMAGE }}
      DOCKERFILE: ${{ matrix.cfg.DOCKERFILE }}
      DOCKERTAG: ${{ matrix.cfg.DOCKERTAG }}
      CUDA_VER: ${{ matrix.cfg.CUDA_VER }}
      CENTOS_VER: ${{ matrix.cfg.CENTOS_VER }}
      MINIFORGE_VARIANT: ${{ matrix.cfg.MINIFORGE_VARIANT }}

    steps:
      - uses: actions/checkout@v2

      - name: Enable experimental features (needed for squash)
        run: |
          sudo cp docker_daemon_config.json /etc/docker/daemon.json
          sudo service docker restart

      - name: Docker info
        run: |
          docker info

      - name: Configure qemu
        run: |
          ./download-qemu-static.sh

      - name: Patch for jnlp-slave
        if: matrix.cfg.DOCKERTAG == 'jnlp-slave'
        run: |
          sed "s|@BASE_IMAGE@|condaforge/$DOCKERIMAGE|" jnlp-slave/Dockerfile.in > $DOCKERIMAGE/Dockerfile

      - name: Build image
        run: |
          docker build \
            --build-arg CUDA_VER --build-arg CENTOS_VER \
            --build-arg MINIFORGE_VARIANT \
            -t condaforge/$DOCKERIMAGE:$DOCKERTAG \
            -f ${DOCKERFILE:-${DOCKERIMAGE}}/Dockerfile \
            --no-cache --squash .

      - name: Run image
        if: matrix.cfg.DOCKERTAG != 'jnlp-slave'
        run: |
          ./.circleci/run_docker_build.sh

      - name: Deploy
        if: github.ref == 'refs/heads/master' && github.repository == 'conda-forge/docker-images'
        env:
          CFD_QUAY_PASSWORD: ${{ secrets.CFD_QUAY_PASSWORD }}
          DH_PASSWORD: ${{ secrets.DH_PASSWORD }}
        run: |
          ./scripts/deploy
