name: Keep
on:
  # pull_request:
  schedule:
    - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC 

jobs:
  keep-alive:
    name: Alive
    if: github.repository == 'conda-forge/docker-images'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@790c7f09285a59b09bb578c85e271c6ff2af97c4
        with:
          commit_message: "Ah ah ah, stayin' alive"
          committer_username: conda-forge-bot
          committer_email: "conda-forge-bot@users.noreply.github.com"
          time_elapsed: 50  # days
